server:
  port: 8080

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000ms
    # 支持发布确认
    publisher-confirms: true
    # 支持发布返回
    publisher-returns: true
    cache:
      channel:
        size: 1


  mail:
    host: smtp.163.com
    username: haohong278636029@163.com
    password: haohong123  #这里是授权码不是登录密码
    protocol: smtp
    default-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.jenkins.own.moudle.*.entity
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "%d -%msg%n"
    file: D://test//test.log
  level:
    com.jenkins.own.moudle.*.dao: DEBUG


